'use client'

import Link from 'next/link'
import { useState } from 'react'

const nav = [['Product','/product'],['Solutions','/solutions'],['Pricing','/pricing'],['Resources','/resources'],['About','/about']]

export function MarketingHeader() {
  const [open, setOpen] = useState(false)
  return <header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-8"><Link href="/" className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground">S</span><span>SyvoRank <span className="text-primary">AI</span></span></Link><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex">{nav.map(([label, href]) => <Link key={href} href={href} className="transition-colors hover:text-foreground">{label}</Link>)}</nav><div className="hidden items-center gap-3 md:flex"><Link href="/signin" className="px-3 py-2 text-sm text-muted-foreground hover:text-foreground">Sign in</Link><Link href="/contact" className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm hover:opacity-90">Book a demo</Link></div><button aria-label="Toggle navigation" onClick={() => setOpen(!open)} className="rounded-lg border border-border px-3 py-2 text-sm md:hidden">Menu</button></div>{open && <nav className="flex flex-col gap-4 border-t border-border px-6 py-5 text-sm md:hidden">{nav.map(([label, href]) => <Link onClick={() => setOpen(false)} key={href} href={href}>{label}</Link>)}<Link href="/signin">Sign in</Link><Link href="/contact" className="font-medium text-primary">Book a demo</Link></nav>}</header>
}

export function MarketingFooter() { return <footer className="border-t border-border bg-muted/30"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 md:grid-cols-[1.5fr_repeat(3,1fr)] lg:px-8"><div><div className="mb-3 font-semibold">SyvoRank <span className="text-primary">AI</span></div><p className="max-w-xs text-sm leading-6 text-muted-foreground">The action-first growth platform for search visibility in the age of AI.</p></div>{[['Product',['Product overview','AI visibility','Content workflow']],['Company',['About us','Resources','Contact']],['Get started',['Book a demo','Sign in','Pricing']]].map(([title, items]) => <div key={title as string}><h3 className="mb-4 text-sm font-semibold">{title as string}</h3><div className="flex flex-col gap-3 text-sm text-muted-foreground">{(items as string[]).map(item => <Link key={item} href={item === 'Sign in' ? '/signin' : item === 'Pricing' ? '/pricing' : item === 'Contact' ? '/contact' : item === 'About us' ? '/about' : item === 'Resources' ? '/resources' : '/product'} className="hover:text-foreground">{item}</Link>)}</div></div>)}</div><div className="mx-auto max-w-7xl border-t border-border px-6 py-5 text-xs text-muted-foreground lg:px-8">© 2026 SyvoRank AI. Built for teams that want to be found.</div></footer> }

export function CTA({title='Turn visibility into momentum.', text='See how SyvoRank AI turns search signals into your next best growth move.'}:{title?:string;text?:string}) { return <section className="mx-auto max-w-7xl px-6 py-20 lg:px-8"><div className="rounded-3xl bg-primary px-8 py-12 text-primary-foreground md:flex md:items-center md:justify-between md:gap-10 md:px-14"><div><p className="mb-3 text-sm font-medium uppercase tracking-[0.18em] text-primary-foreground/70">Ready when you are</p><h2 className="max-w-xl text-balance text-3xl font-semibold tracking-tight md:text-4xl">{title}</h2><p className="mt-4 max-w-lg leading-7 text-primary-foreground/75">{text}</p></div><Link href="/contact" className="mt-8 inline-flex shrink-0 rounded-lg bg-background px-5 py-3 text-sm font-medium text-foreground md:mt-0">Talk to our team</Link></div></section> }

export function SiteFrame({children}:{children:React.ReactNode}) { return <><MarketingHeader />{children}<MarketingFooter /></> }

export const eyebrow = 'text-sm font-medium uppercase tracking-[0.18em] text-primary'
export const section = 'mx-auto max-w-7xl px-6 lg:px-8'
